apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: vulnerability-service
  namespace: {{ .Values.namespaces.vulnerabilityservice}} 
spec:
  selector:
    matchLabels:
      app: vulnerability-service
  jwtRules:
  - issuer: {{ .Values.jwtRules.issuer}} 
    jwksUri: {{ .Values.jwtRules.jwksUri}} 
    
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: vulnerability-service
  namespace: {{ .Values.namespaces.vulnerabilityservice}}
spec:
  selector:
    matchLabels:
      app: vulnerability-service
  action: CUSTOM
  provider:
    name: accuknox-ext-authz-http
  rules:
  - to:
    - operation:
        paths: ["/vulnerabilityservice/api/*"]